server:
  port: 8002

spring:
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

static:
  path: https://localhost:8002/static    # 静态路径地址